### ISSUE TITLE
Building the DjiNN server

### ISSUE THREAD

**Issue by knkrth** [claritylab/djinn#2]
Hi, when i try to build using make -j 4 i got the following error i'm using latest caffe version

kartx@kartx-VirtualBox:~/Desktop/djinn-master/service$ make -j 4

g++ -c -g -I/usr/local/include -fpermissive -I../common/include -I/home/kartx/Downloads/caffe-master/include -I/usr/local/cuda/include -DCPU_ONLY src/main.cpp -o src/main.o
src/main.cpp: In function ‘int main(int, char*_)’:
src/main.cpp:88:42: error: no matching function for call to ‘caffe::Net<float>::Net(std::__cxx11::string&)’
     Net<float>_ temp = new Net<float>(net);
                                          ^
In file included from /home/kartx/Downloads/caffe-master/include/caffe/blob.hpp:8:0,
                 from /home/kartx/Downloads/caffe-master/include/caffe/caffe.hpp:7,
                 from src/thread.h:22,
                 from src/main.cpp:29:
/home/kartx/Downloads/caffe-master/include/caffe/net.hpp:309:27: note: candidate: caffe::Net<Dtype>::Net(const caffe::Net<Dtype>&) [with Dtype = float]
   DISABLE_COPY_AND_ASSIGN(Net);
                           ^
/home/kartx/Downloads/caffe-master/include/caffe/common.hpp:33:3: note: in definition of macro ‘DISABLE_COPY_AND_ASSIGN’
   classname(const classname&);\
   ^
/home/kartx/Downloads/caffe-master/include/caffe/net.hpp:309:27: note:   no known conversion for argument 1 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘const caffe::Net<float>&’
   DISABLE_COPY_AND_ASSIGN(Net);
                           ^
/home/kartx/Downloads/caffe-master/include/caffe/common.hpp:33:3: note: in definition of macro ‘DISABLE_COPY_AND_ASSIGN’
   classname(const classname&);\
   ^
In file included from /home/kartx/Downloads/caffe-master/include/caffe/caffe.hpp:12:0,
                 from src/thread.h:22,
                 from src/main.cpp:29:
/home/kartx/Downloads/caffe-master/include/caffe/net.hpp:27:12: note: candidate: caffe::Net<Dtype>::Net(const string&, caffe::Phase, const caffe::Net<Dtype>_) [with Dtype = float; std::__cxx11::string = std::__cxx11::basic_string<char>]
   explicit Net(const string& param_file, Phase phase,
            ^
/home/kartx/Downloads/caffe-master/include/caffe/net.hpp:27:12: note:   candidate expects 3 arguments, 1 provided
/home/kartx/Downloads/caffe-master/include/caffe/net.hpp:26:12: note: candidate: caffe::Net<Dtype>::Net(const caffe::NetParameter&, const caffe::Net<Dtype>_) [with Dtype = float]
   explicit Net(const NetParameter& param, const Net\* root_net = NULL);
            ^
/home/kartx/Downloads/caffe-master/include/caffe/net.hpp:26:12: note:   no known conversion for argument 1 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘const caffe::NetParameter&’
Makefile:39: recipe for target 'src/main.o' failed
make: **\* [src/main.o] Error 1
kartx@kartx-VirtualBox:~/Desktop/djinn-master/service$

**Comment by jhauswald** [comment]
Djinn most likely doesn't build with caffe's latest version considering how quickly their code changes, use the package we have on the [website](http://djinn.clarity-lab.org/downloads/).

**Comment by knkrth** [comment]
Thanks, using  caffe-1.0 everything works well.

**Comment by knkrth** [comment]
@haoyifan Did you find any solution for Segmentation fault (core dumped) i have tried all possible solution but non works.

**Comment by haoyifan** [comment]
Did you modify the value of GPU_ONLY in the configure file? I also modify the variable value but it still prompts me with segmentation fault.

Actually I'm stuck with my linux. It seems that the gpu of my computer does not fit with cuda. Whenever I install cuda driver, the screen would turn black when I reboot my linux. I have reinstalled djinn three times. Have you met this problem?

**Comment by knkrth** [comment]
@haoyifan No i don't have GPU's because i'm on virtual box (ubuntu 15.01) & I use CPU_ONLY on both Djinn and caffe. Make sure you have change both Djinn & caffe to GPU_ONLY.

**Comment by haoyifan** [comment]
By GPU, I mean the GPU of my own computer. My computer GPU is AMD Radeon R9 M370X 2048 MB. When I install CUDA, it will modify some files of the gpu, which will cause the black screen problem.

Yeah I changed both of the flags but it still doesn't work.

**Comment by knkrth** [comment]
when i use the back track to find the error i got this

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xa4e45b40 (LWP 1768)]
0x08064680 in reshape(caffe::Net<float>_, int) ()
(gdb) bt
#0  0x08064680 in reshape(caffe::Net<float>_, int) ()
#1  0x08052434 in request_handler (sock=0x5) at src/thread.cpp:101
#2  0xb7fa11aa in start_thread (arg=0xa4e45b40) at pthread_create.c:333
#3  0xb7ab7fde in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:122

**Comment by haoyifan** [comment]
Hi kartx

Have you figured out the seg fault problem? I just reinstalled the djinn and it didn't prompt me with the seg fault.

**Comment by haoyifan** [comment]
Make sure you uncomment the CPU_ONLY variable in both Make.configure file before install the application

**Comment by knkrth** [comment]
@haoyifan ok i did try thanks for your help but now i'm working on cloud i don't have any problem in there. Its seems to be some problem on my system.

**Comment by knkrth** [comment]
@haoyifan Are you working on djinn to link with lucida ecosystem?

**Comment by haoyifan** [comment]
I'm still configuring the right thrift in my machine.

**Comment by tyayoutyan** [comment]
CUDA is only for Nvidia GPU.
